apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-{{ .Release.Name }}-dep
  labels:
    app: drive
spec:
  serviceName: {{ .Release.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: drive       # this seems necessary as well to get the app: drive label onto the pvc? (even though this is a selector and the app-release selector should be enough?)
      app-release: nfs-{{ .Release.Name }}-pod
  template:
    metadata:
      labels:
        app: drive
        app-release: nfs-{{ .Release.Name }}-pod
    spec:
      nodeSelector:
        hub.jupyter.org/node-purpose: core   # install on same nodes as jupyterhub core services
      securityContext:
        runAsUser: 0
        fsGroup: 0

      containers:
      - name: nfs
        resources: 
          requests:
            cpu: 0.1
            memory: "128M"
          limits:
            cpu: 0.5
            memory: "2G"
        image: oneilsh/ktesting-nfsserver3:acb20051
        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "SETPCAP"]
          #runAsUser: 0
          #fsGroup: 0
        volumeMounts:
        - mountPath: "/nfsshare"   # it seems the shared dir must be a volume mount, see https://github.com/kubernetes/kubernetes/issues/19593#issuecomment-417106013
          name: storagevol
  volumeClaimTemplates:
  - metadata:
      name: storagevol
      labels: 
        app: drive
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ index .Values "nfs-drive" "size" }} 
