apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nfs-{{ .Release.Name }}-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-{{ .Release.Name }}-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-{{ .Release.Name }}-pod
    spec:
      volumes:
      - name: pvol-{{ .Release.Name }}
        persistentVolumeClaim:
          claimName: pvclaim-{{ .Release.Name }}
      containers:
      - name: nfs
        image: oneilsh/ktesting-nfsserver3
        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "SETPCAP"]
        volumeMounts:
        - mountPath: "/nfsshare"   # it seems the shared dir must be a volume mount, see https://github.com/kubernetes/kubernetes/issues/19593#issuecomment-417106013
          name: pvol-{{ .Release.Name }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvclaim-{{ .Release.Name }}
spec:
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests: 
      storage: {{ .Values.size }}
  
