apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-master-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
spec:
  tls:
  - hosts:
    - {{ index .Values "nginx-ingress" "masterHost" }} # how to handle dashes in subchart names: https://github.com/helm/helm/issues/2192#issuecomment-306033149
  rules:
  - host: {{ index .Values "nginx-ingress" "masterHost" }}
