apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
data:
  file.system.id: {{ .Values.efsFilesystemId }}
  aws.region: {{ .Values.efsRegion }}
  provisioner.name: {{ .Values.efsProvisionerName }} 
  dns.name: ""
