{{- if .Values.ingress.enabled -}}
## FUTURE: When k8s 1.20 is released or when we can assume k8s 1.14, switch from
##         apiVersion: extensions/v1beta1 to using apiVersion:
##         networking.k8s.io/v1beta1.
##
## ref: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
##
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
    # TODO: in helm v2, .Release.Name must be unique cluster-wide, so using both release name and
    # namespace for identification isn't necessary. In future versions of rancher + helm3 this should
    # be enabled. We may then want to identify applications by path, rather than subdomain, to avoid
    # getting crazy deep subdomains (e.g. as bad as app.namespace.cluster.dsinfra.org.edu)
    # using default host, which should match anything and be handled by the ingress controller; we just need the CNAME (e.g. cluster4.dsosu.us) to point to the ELB, then we can 
    # hopefully contact this service at cluster4.dsosu.us/namespace/releasename
    #- host: {{ .Release.Name }}.{{ .Release.Namespace }}.{{ .Values.ingress.domain }}
    - http:
        paths:
          - path: /{{ .Release.Namespace }}/{{ .Release.Name }}{{ $.Values.hub.baseUrl }}{{ $.Values.ingress.pathSuffix }}
            backend:
              serviceName: proxy-public
              servicePort: 80
      host: eksdevc.dsosu.us
  {{- if .Values.ingress.tls }}
  tls:
    {{- .Values.ingress.tls | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
{{- end }}
