apiVersion: v1
kind: Pod
metadata:
  name: singleuser-pod
  labels:
    app: jh
spec:
  volumes:
   - name: start-vol
     configMap:
       name: start
   - name: mount-home-nfs-vol
     configMap:
       name: mount-home-nfs
  containers:
  - name: jh-container
    image: oneilsh/ktesting-base-notebook:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /usr/local/bin/start-notebook.d/mount_home_nfs.sh
      subPath: mount_home_nfs.sh
      name: mount-home-nfs-vol
    - mountPath: /usr/local/bin/start.sh
      subPath: start.sh
      name: start-vol
    env:
      #- name: NFS_HOME_SVC
      #  value: "homdrive"
      #- name: NB_USER
      #  value: "oneils"
      #- name: NB_UID
      #  value: "1000"
      #- name: CHOWN_HOME
      #  value: "yes"
      #- name: CHOWN_HOME_OPTS
      #  value: "-R"
    securityContext:
      runAsUser: 0
      capabilities:
        add: ["SYS_ADMIN"]
