apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: limittest-home-copy-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 20Gi
  volumeName: limittest-home-copy-pv
