apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nfs-studentvol-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-studentvol-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-studentvol-pod
    spec:
      volumes:
      - emptyDir: {}
        name: nfsshare
      containers:
      - name: nfs
        image: oneilsh/ktesting-nfsserver3
        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "SETPCAP"]
        volumeMounts:
        - mountPath: "/nfsshare"   # it seems the shared dir must be a volume mount, see https://github.com/kubernetes/kubernetes/issues/19593#issuecomment-417106013
          name: nfsshare
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef: 
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP

---

apiVersion: v1
kind: Service
metadata:
  name: nfs-studentvol-getip-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nfs-studentvol-pod

---

apiVersion: v1
kind: Service
metadata:
  name: nfs-studentvol-nfs-svc
spec:
  type: ClusterIP
  selector:
    app: nfs-studentvol-pod
  ports:
  - port: 111
    protocol: UDP
    name: udp111
  - port: 2049
    protocol: TCP
    name: tcp2049


---

apiVersion: v1
kind: Pod
metadata:
  name: clientpod
spec:
  containers:
  - name: clientpod-con
    image: oneilsh/ktesting-nfsclient
    env:
    - name: GETIP_SVC
      value: nfs-studentvol-getip-svc
    - name: NFS_SVC
      value: nfs-studentvol-nfs-svc
    securityContext:
      capabilities:
        add: ["SYS_ADMIN", "SETPCAP"]

