#!/bin/bash

if [[ "$#" == "0" ]] || [[ "$1" == "-h" ]]; then
  echo "Usage: hubpip install package1 package2 ..."
  echo "This just calls \`pip install --prefix=$ADMIN_HOME_DIR/python_libs package1 package2 ...\` in case you need to do anything fancy."
  exit 1
fi

echo -e "\e[32mhubpip: Running \`pip $1 --prefix=$ADMIN_HOME_DIR/python_libs ${@:2}\` ...\e[0m"
pip $1 --prefix=$ADMIN_HOME_DIR/python_libs ${@:2}

echo -e "\e[32mhubpip: Fixing permissions ...\e[0m"
chgrp -R $ADMIN_GROUPNAME $ADMIN_HOME_DIR/python_libs 2> /dev/null

chmod -R 775 $ADMIN_HOME_DIR/python_libs 2> /dev/null
echo -e "\e[32mhubpip: Done. Enjoy your package!\e[0m"
