apiVersion: v1
kind: Pod
metadata:
  name: singleuser-pod
  labels:
    app: jh
spec:
  volumes:
   - name: start-vol
     configMap:
       name: start
   - name: start-notebook-d-vol
     configMap:
       name: start-notebook-d
  containers:
  - name: jh-container
    image: oneilsh/ktesting-base-notebook:latest
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /usr/local/bin/start-notebook.d/
      name: start-notebook-d-vol
    - mountPath: /usr/local/bin/start.sh
      subPath: start.sh
      name: start-vol
    env:
      - name: NFS_SVC
        value: "nfsdrive"
      - name: NB_USER
        value: juser
    securityContext:
      runAsUser: 0
      capabilities:
        add: ["SYS_ADMIN"]
