apiVersion: v1
kind: Pod
metadata:
  name: singleuser-pod
  labels:
    app: jh
spec:
  volumes:
   - name: start-vol
     configMap:
       name: start-cm
   - name: various-vol
     configMap:
       name: various-cm
  containers:
  - name: jh-container
    image: oneilsh/ktesting-datascience-notebook:latest
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /usr/local/bin/various/
      name: various-vol
    - mountPath: /usr/local/bin/start.sh
      subPath: start.sh
      name: start-vol
    env:
      - name: NFS_SVC_HOME
        value: "nfsdrive"
      - name: NB_USER
        value: juser
      - name: ADMIN_USER
        value: "True"
    securityContext:
      runAsUser: 0
      capabilities:
        add: ["SYS_ADMIN"]
