{
 "title": "JHub Cluster Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_labels, namespace)"
   },
   {
    "name": "nodetype",
    "query": "label_values(kube_node_labels, label_beta_kubernetes_io_instance_type)"
   }
  ]
 },
 "panels": [
  { "title": "Node Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NodePool Sizes",
   "type": "graph",
   "description": "Number of nodes per nodepool, grouped by labels and instance types.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "count (kube_node_labels) by (label_alpha_eksctl_io_nodegroup_name, label_beta_kubernetes_io_instance_type, label_hub_jupyter_org_node_purpose)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}/{{label_hub_jupyter_org_node_purpose}}"
    }
   ]
  },
  {
   "title": "SingleUser Servers per Node",
   "type": "graph",
   "description": "Number of singleuser servers running per node.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_labels{label_component=\"singleuser-server\"}) by(node) * on(node) group_right() kube_node_labels",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Node Utilization CPU Request -- ${nodetype}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "repeat": "nodetype",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# I don't know why \"${nodetype:csv}\" works but \"${nodetype:regex}\" doesn't...\n(sum(kube_pod_container_resource_requests_cpu_cores) by (node)) \n / (sum(kube_node_status_allocatable_cpu_cores) by (node)) \n * on(node) group_right() kube_node_labels{label_beta_kubernetes_io_instance_type=~\"${nodetype:csv}\"}",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Node Utilization CPU Request -- ${nodetype}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# I don't know why \"${nodetype:csv}\" works but \"${nodetype:regex}\" doesn't...\n(sum(kube_pod_container_resource_requests_cpu_cores) by (node)) \n / (sum(kube_node_status_allocatable_cpu_cores) by (node)) \n * on(node) group_right() kube_node_labels{label_beta_kubernetes_io_instance_type=~\"${nodetype:csv}\"}",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Node Utilization Memory Request -- ${nodetype}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "repeat": "nodetype",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# I don't know why \"${nodetype:csv}\" works but \"${nodetype:regex}\" doesn't...\n(sum(kube_pod_container_resource_requests_memory_bytes) by (node)) \n / (sum(kube_node_status_allocatable_memory_bytes) by (node)) \n * on(node) group_right() kube_node_labels{label_beta_kubernetes_io_instance_type=~\"${nodetype:csv}\"}",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Node Utilization Memory Request -- ${nodetype}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# I don't know why \"${nodetype:csv}\" works but \"${nodetype:regex}\" doesn't...\n(sum(kube_pod_container_resource_requests_memory_bytes) by (node)) \n / (sum(kube_node_status_allocatable_memory_bytes) by (node)) \n * on(node) group_right() kube_node_labels{label_beta_kubernetes_io_instance_type=~\"${nodetype:csv}\"}",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Node Utilization RSS -- ${nodetype}",
   "type": "graph",
   "description": "Node memory utilization by resident set size.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "repeat": "nodetype",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# I don't know why \"${nodetype:csv}\" works but \"${nodetype:regex}\" doesn't...\n(sum(container_memory_rss) by (node)  / (sum(kube_node_status_allocatable_memory_bytes) by (node))) * on(node) group_right() kube_node_labels{label_beta_kubernetes_io_instance_type=~\"${nodetype:csv}\"}",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "Node Utilization RSS -- ${nodetype}",
   "type": "graph",
   "description": "Node memory utilization by resident set size.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# I don't know why \"${nodetype:csv}\" works but \"${nodetype:regex}\" doesn't...\n(sum(container_memory_rss) by (node)  / (sum(kube_node_status_allocatable_memory_bytes) by (node))) * on(node) group_right() kube_node_labels{label_beta_kubernetes_io_instance_type=~\"${nodetype:csv}\"}",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  { "title": "Volume Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Space Usage per Namespace",
   "type": "graph",
   "description": "Total data *used*, not allocated, per namespace.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{exported_namespace=~\"${namespace:regex}\"}) by(exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  { "title": "Pod Information - ${namespace}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }, "repeat": "namespace" },
  {
   "title": "Memory Use (singleuser servers) -- ${namespace}",
   "type": "graph",
   "description": "For each singleuser pod, shows the RSS (resident set size) over the Request size (which may be greater than 1), and the RSS / Limit (which must be 0 to 1). To Make the plot clearer, RSS/Limit is shown flipped below the 0 axis. ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    {
     "format": "short",
     "label": "RSS/Request, RSS/Limit (below 0)"
    }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_rss) by(pod, namespace)) / on(pod, namespace) (sum(kube_pod_container_resource_requests_memory_bytes) by(pod, namespace)) * on(pod, namespace) kube_pod_labels{label_component=\"singleuser-server\", namespace=\"${namespace:regex}\"}",
     "legendFormat": "RSS/Request: {{namespace}}/{{pod}}"
    },
    {
     "expr": "(sum(container_memory_rss) by(pod, namespace)) / on(pod, namespace) (sum(kube_pod_container_resource_limits_memory_bytes) by(pod, namespace)) * on(pod, namespace) kube_pod_labels{label_component=\"singleuser-server\", namespace=\"${namespace:regex}\"}",
     "legendFormat": "RSS/Limit: {{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Jupyterhub Pod Types -- ${namespace}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "count (kube_pod_labels{label_app=\"jupyterhub\",namespace=~\"${namespace:regex}\"}) by (label_component) ",
     "legendFormat": "{{label_component}}"
    }
   ]
  },
  { "title": "Pod Information - ${namespace}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Memory Use (singleuser servers) -- ${namespace}",
   "type": "graph",
   "description": "For each singleuser pod, shows the RSS (resident set size) over the Request size (which may be greater than 1), and the RSS / Limit (which must be 0 to 1). To Make the plot clearer, RSS/Limit is shown flipped below the 0 axis. ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    {
     "format": "short",
     "label": "RSS/Request, RSS/Limit (below 0)"
    }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_rss) by(pod, namespace)) / on(pod, namespace) (sum(kube_pod_container_resource_requests_memory_bytes) by(pod, namespace)) * on(pod, namespace) kube_pod_labels{label_component=\"singleuser-server\", namespace=\"${namespace:regex}\"}",
     "legendFormat": "RSS/Request: {{namespace}}/{{pod}}"
    },
    {
     "expr": "(sum(container_memory_rss) by(pod, namespace)) / on(pod, namespace) (sum(kube_pod_container_resource_limits_memory_bytes) by(pod, namespace)) * on(pod, namespace) kube_pod_labels{label_component=\"singleuser-server\", namespace=\"${namespace:regex}\"}",
     "legendFormat": "RSS/Limit: {{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Jupyterhub Pod Types -- ${namespace}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "count (kube_pod_labels{label_app=\"jupyterhub\",namespace=~\"${namespace:regex}\"}) by (label_component) ",
     "legendFormat": "{{label_component}}"
    }
   ]
  }
 ]
}