apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-master-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
spec:
  tls:
  - hosts:
    - {{ .Values.master-host }}
  rules:
  - host: {{ .Values.master-host }}
