{
 "title": "JHub Cluster Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_labels, namespace)"
   },
   {
    "name": "nodetype",
    "query": "label_values(kube_node_labels, label_hub_jupyter_org_node_purpose)"
   },
   {
    "name": "namespaces_no_system",
    "query": "label_values(kube_pod_labels, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "User Pods Per Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "User Pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_component=\"singleuser-server\", namespace=~\"${namespace:regex}\" }) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Node Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "NodePool Sizes",
   "type": "graph",
   "description": "Number of nodes per nodepool, grouped by labels and instance types.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "count (kube_node_labels) by (label_alpha_eksctl_io_nodegroup_name , label_beta_kubernetes_io_instance_type, label_hub_jupyter_org_node_purpose)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}/{{label_hub_jupyter_org_node_purpose}}"
    }
   ]
  },
  {
   "title": "Node Utilization CPU Request -- ${nodetype}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "repeat": "nodetype",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# I don't know why \"${nodetype:csv}\" works but \"${nodetype:regex}\" doesn't...\n(sum(kube_pod_container_resource_requests_cpu_cores) by (node)) \n / (sum(kube_node_status_allocatable_cpu_cores) by (node)) \n * on(node) group_right() kube_node_labels{label_hub_jupyter_org_node_purpose=~\"${nodetype:regex}\"}"
    }
   ]
  },
  {
   "title": "Node Utilization CPU Request -- ${nodetype}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# I don't know why \"${nodetype:csv}\" works but \"${nodetype:regex}\" doesn't...\n(sum(kube_pod_container_resource_requests_cpu_cores) by (node)) \n / (sum(kube_node_status_allocatable_cpu_cores) by (node)) \n * on(node) group_right() kube_node_labels{label_hub_jupyter_org_node_purpose=~\"${nodetype:regex}\"}"
    }
   ]
  },
  {
   "title": "Node Utilization Memory Request -- ${nodetype}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "repeat": "nodetype",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# I don't know why \"${nodetype:csv}\" works but \"${nodetype:regex}\" doesn't...\n(sum(kube_pod_container_resource_requests_memory_bytes) by (node)) \n / (sum(kube_node_status_allocatable_memory_bytes) by (node)) \n * on(node) group_right() kube_node_labels{label_hub_jupyter_org_node_purpose=~\"${nodetype:csv}\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Utilization Memory Request -- ${nodetype}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# I don't know why \"${nodetype:csv}\" works but \"${nodetype:regex}\" doesn't...\n(sum(kube_pod_container_resource_requests_memory_bytes) by (node)) \n / (sum(kube_node_status_allocatable_memory_bytes) by (node)) \n * on(node) group_right() kube_node_labels{label_hub_jupyter_org_node_purpose=~\"${nodetype:csv}\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Utilization RSS -- ${nodetype}",
   "type": "graph",
   "description": "Node memory utilization by resident set size.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "repeat": "nodetype",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_rss) by (node)  / (sum(kube_node_status_allocatable_memory_bytes) by (node))) ",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Node Utilization RSS -- ${nodetype}",
   "type": "graph",
   "description": "Node memory utilization by resident set size.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_rss) by (node)  / (sum(kube_node_status_allocatable_memory_bytes) by (node))) ",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  { "title": "Volume Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Space Usage per Namespace",
   "type": "graph",
   "description": "Total data *used*, not allocated, per namespace.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"${namespace:regex}\"}) by(namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Pod Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Memory Use (singleuser servers) -- ${namespaces_no_system}",
   "type": "graph",
   "description": "For each singleuser pod, shows the RSS (resident set size) over the Request size (which may be greater than 1), and the RSS / Limit (which must be 0 to 1). To Make the plot clearer, RSS/Limit is shown flipped below the 0 axis. ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "repeat": "namespaces_no_system",
   "yaxes": [
    { "format": "short", "label": "RSS/Request" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_rss) by(pod, namespace)) / on(pod, namespace) (sum(kube_pod_container_resource_requests_memory_bytes) by(pod, namespace)) * on(pod, namespace) kube_pod_labels{label_component=\"singleuser-server\", namespace=\"${namespaces_no_system:regex}\"}",
     "legendFormat": "RSS/Request: {{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Use (singleuser servers) -- ${namespaces_no_system}",
   "type": "graph",
   "description": "For each singleuser pod, shows the RSS (resident set size) over the Request size (which may be greater than 1), and the RSS / Limit (which must be 0 to 1). To Make the plot clearer, RSS/Limit is shown flipped below the 0 axis. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "repeat": "namespaces_no_system",
   "yaxes": [
    {
     "format": "short",
     "label": "RSS/Request, RSS/Limit (below 0)"
    }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_rss) by(pod, namespace)) / on(pod, namespace) (sum(kube_pod_container_resource_limits_memory_bytes) by(pod, namespace)) * on(pod, namespace) kube_pod_labels{label_component=\"singleuser-server\", namespace=\"${namespaces_no_system:regex}\"}",
     "legendFormat": "RSS/Limit: {{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}