# requires helm-kush plugin from https://github.com/oneilsh/helm-kush

# example deployment:
# helm kush upgrade master-ingress ../charts/nginx-ingress --install --kush-interpolate --values <thisfile>

kubeContext: hub-green
createNamespace: cluster-tools

nginx-ingress:
  masterHost: hub-green.datasci.oregonstate.edu
  controller:
    defaultTLS:
      cert:  <%= $( /usr/bin/base64 -w 0 /datascience/keys/ssl/__datasci_oregonstate_edu.pem) %>
      key:  <%= $( /usr/bin/base64 -w 0 /datascience/keys/ssl/private.key) %>
    wildcardTLS:
      cert:  <%= $( /usr/bin/base64 -w 0 /datascience/keys/ssl/__datasci_oregonstate_edu.pem) %>
      key:  <%= $( /usr/bin/base64 -w 0 /datascience/keys/ssl/private.key) %>
    nodeSelector:
      nodegroup-role: clustertools
    config:
      entries:
        client-max-body-size: 2G
