#!/usr/bin/env -S helm kush upgrade master-ingress /datascience/dsosuk8s/charts/nginx-ingress --install --kush-interpolate --values
#!/usr/bin/env -S helm kush template master-ingress /datascience/dsosuk8s/charts/nginx-ingress --kush-interpolate --values

kubeContext: hub-green
createNamespace: cluster-tools

nginx-ingress:
  masterHost: hub-green.datasci.oregonstate.edu
  controller:
    defaultTLS:
      cert:  <%= $( /usr/bin/base64 -w 0 /datascience/keys/ssl/__datasci_oregonstate_edu.pem) %>
      key:  <%= $( /usr/bin/base64 -w 0 /datascience/keys/ssl/private.key) %>
    wildcardTLS:
      cert:  <%= $( /usr/bin/base64 -w 0 /datascience/keys/ssl/__datasci_oregonstate_edu.pem) %>
      key:  <%= $( /usr/bin/base64 -w 0 /datascience/keys/ssl/private.key) %>
    nodeSelector:
      nodegroup-role: clustertools
    config:
      entries:
        client-max-body-size: 2G
