# requires helm-kush plugin from https://github.com/oneilsh/helm-kush

# example deployment:
# helm kush upgrade prometheus ../charts/prometheus --kush-interpolate --install --values <thisfile>

# uninstall: helm delete prometheus -n cluster-tools 

kubeContext: hub-green
createNamespace: cluster-tools

configmapReload:
  prometheus:
    image: 
      repository: localhost:30050/jimmidyson/configmap-reload
  alertmanager:
    image: 
      repository: localhost:30050/jimmidyson/configmap-reload

pushgateway:
  image:
    repository: localhost:30050/prom/pushgateway
  nodeSelector:
    nodegroup-role: clustertools

kubeStateMetrics:
  nodeSelector:
    nodegroup-role: clustertools
  service:
    annotations: {}
  labels: {}

alertmanager:
  image: 
    repository: localhost:30050/prom/alertmanager
  nodeSelector:
    nodegroup-role: clustertools

server:
  image:
    repository: localhost:30050/prom/prometheus
  nodeSelector:
    nodegroup-role: clustertools
  resources:
    limits:
      cpu: 1000m
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 2Gi

nodeExporter:
  image:
    repository: localhost:30050/prom/node-exporter
  tolerations:
  - effect: NoSchedule
    key: hub.jupyter.org/dedicated
    operator: Equal
    value: user
  - effect: NoSchedule
    key: hub.jupyter.org_dedicated
    operator: Equal
    value: user
