apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: busybox
    args: 
    - sleep
    - "100000"
  imagePullSecrets:
  - name: regcred
