nginx-ingress:
  controller:
    config:
      use-proxy-protocol: "False"
      use-forwarded-headers: "True"
      proxy-real-ip-cidr: "0.0.0.0/0" # restrict this to the IP addresses of ELB 
      #ssl-redirect: "true"
      # per https://github.com/nginxinc/kubernetes-ingress/issues/358#issuecomment-418973875
      redirect-to-https: "True"
      proxy-connect-timeout: "3600s"
      proxy-read-timeout: "3600s"
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:XX-XXXX-X:XXXXXXXXX:certificate/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
      externalTrafficPolicy: Cluster
      # since we're doing ssl termination in the load balancer
      targetPorts:
        http: http
        https: http 

