apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-{{ .Release.Name }}-dep
spec:
  serviceName: {{ .Release.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: nfs-{{ .Release.Name }}-pod
  template:
    metadata:
      labels:
        app: nfs-{{ .Release.Name }}-pod
    spec:
      nodeSelector:
        volatile: "false"   # require non-volatile nodes (won't be autoscaled out frequently, as this will disrupt service to this drive)
      securityContext:
        runAsUser: 0
        fsGroup: 0

      containers:
      - name: nfs
        resources: 
          requests:
            cpu: 0.1
            memory: "128M"
          limits:
            cpu: 0.5
            memory: "2G"
        image: oneilsh/ktesting-nfsserver3:acb20051
        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "SETPCAP"]
          #runAsUser: 0
          #fsGroup: 0
        volumeMounts:
        - mountPath: "/nfsshare"   # it seems the shared dir must be a volume mount, see https://github.com/kubernetes/kubernetes/issues/19593#issuecomment-417106013
          name: storagevol
  volumeClaimTemplates:
  - metadata:
      name: storagevol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.size }} 
