apiVersion: v1
appVersion: 6.6.0
description: The leading tool for querying and visualizing time series and metrics. (Fork for custom deployment by Shawn O'Neil)
engine: gotpl
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
kubeVersion: ^1.8.0-0
maintainers:
- email: zanhsieh@gmail.com
  name: zanhsieh
- email: rluckie@cisco.com
  name: rtluckie
- email: maor.friedman@redhat.com
  name: maorfr
- email: shawn.oneil@oregonstate.edu
  name: Shawn T O'Neil
name: grafana
sources:
- https://github.com/grafana/grafana
tillerVersion: '>=2.12.0'
version: 4.6.3
