
oauth2-proxy:
  config:
    existingSecret: ""
    ingress:
      enabled: true
      path: /oauth2
      hosts:
      - oauth2.dsosu.us
    httpScheme: https
    extraArgs:
      whitelist-domain: .dsosu.us
      cookie-domain: .dsosu.us
      http-address: 0.0.0.0:4180
      #provider: oidc
      redirect-url: https://oauth2.dsosu.us/oauth2/callback
      #oidc-issuer-url: https://dex.example.org/
      cookie-secure: false
      email-domain: "*"
      #cookie-domain: .example.org
      pass-access-token: true
      pass-authorization-header: true
      skip-provider-button: false
      #whitelist-domain: .example.org
      #http-address: 0.0.0.0:4180
      set-authorization-header: true
      set-xauthrequest: true
      skip-auth-preflight: false
    #service:
    #  port: 443
