apiVersion: v1
description: JupyerLab with Python, Julia, R, RStudio, Shiny
icon: file://icon.svg
keywords:
- jupyter
- lab
- python
- R
- julia
- rstudio
- shiny
maintainers:
- email: shawn.oneil@oregonstate.edu
  name: Shawn T O'Neil
name: ds-jupyterlab
version: 1.3.5
changeLog:
  v1.3.5:
    patch:
    - temp bugfix for home dirs having g+s set
  v1.3.4:
    patch:
    - cost-based autoscaling group preferences
    - increased timeout for user pod spawn, increase simultaneous spawn limit
  v1.3.3:
    patch:
    - taking hub_db dir off of nfs for stability
  v1.3.2:
    patch:
    - fixing shiny server
  v1.3.1:
    patch:
    - refactored start.sh and volume files
    minor: 
    - user admin can be switched on/off (requires user-server restart)
  v1.2.0:
    minor: 
    - Update deploy scripts to use more defaults.
  v1.1.2:
    patch: 
    - slight cleanup values.yaml and deploy scripts
  v1.1.1: 
    major:
    - First properly versioned chart (yay)
    minor:
    - Recently working RAM meter in user UI
    - Added ability for admins to install JLab extensions (needs ~2G RAM to build)
