apiVersion: v1
description: JupyerLab with Python, Julia, R, RStudio, Shiny
icon: file://icon.svg
keywords:
- jupyter
- lab
- python
- R
- julia
- rstudio
- shiny
maintainers:
- email: shawn.oneil@oregonstate.edu
  name: Shawn T O'Neil
name: ds-jupyterlab
version: 2.1.0-dev
changeLog:
  v2.1.0:
    minor: 
    - Updating dependencies on k8s-network-tools, k8s-image-awaiter, configurable-http-proxy, jupyterlab-k8s-hub, and singleuser image to cjkeist/jupyterlab-ubuntu 1.0.2-dev
  v2.0.0:
    major:
    - Update backing jupyterhub helm chart to 2.3.0
  v1.6.0:
    minor:
    - Update autosourced_by_rprofiles.R to work with R 4.1:w
  v1.5.1:
    minor:
    - new deployment strategy via helm plugin
    - dynamic profile generation/selection
  v1.4.1:
    minor:
    - allow for GPU requests with GPU_COUNT
    - allow choice for SINGLEUSER_IMAGE, SINGLEUSER_IMAGE_TAG, HUB_IMAGE and HUB_IMAGE_TAG
  v1.3.5:
    patch:
    - temp bugfix for home dirs having g+s set
  v1.3.4:
    patch:
    - cost-based autoscaling group preferences
    - increased timeout for user pod spawn, increase simultaneous spawn limit
  v1.3.3:
    patch:
    - taking hub_db dir off of nfs for stability
  v1.3.2:
    patch:
    - fixing shiny server
  v1.3.1:
    patch:
    - refactored start.sh and volume files
    minor: 
    - user admin can be switched on/off (requires user-server restart)
  v1.2.0:
    minor: 
    - Update deploy scripts to use more defaults.
  v1.1.2:
    patch: 
    - slight cleanup values.yaml and deploy scripts
  v1.1.1: 
    major:
    - First properly versioned chart (yay)
    minor:
    - Recently working RAM meter in user UI
    - Added ability for admins to install JLab extensions (needs ~2G RAM to build)
