apiVersion: v1
description: JupyerLab with Python, Julia, R, RStudio, Shiny
engine: gotpl
home: https://github.com/oneilsh/ktesting
icon: file://icon.svg
keywords:
- jupyter
- lab
- python
- R
- julia
- rstudio
- shiny
maintainers:
- email: oneilsh@gmail.com
  name: Shawn
name: ds-jupyterlab
sources:
- https://github.com/oneilsh/ktesting
version: 1.1.1+4dba869
