apiVersion: v1
description: JupyerLab with Python, Julia, R, RStudio, Shiny
icon: file://icon.svg
keywords:
- jupyter
- lab
- python
- R
- julia
- rstudio
- shiny
maintainers:
- email: shawn.oneil@oregonstate.edu
  name: Shawn T O'Neil
name: ds-jupyterlab
version: 1.2.0
changeLog:
  v1.2.0:
    minor: 
    - Update deploy scripts to use more defaults.
  v1.1.2:
    patch: 
    - slight cleanup values.yaml and deploy scripts
  v1.1.1: 
    major:
    - First properly versioned chart (yay)
    minor:
    - Recently working RAM meter in user UI
    - Added ability for admins to install JLab extensions (needs ~2G RAM to build)
