---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUCPEbKmz7X5y9mQ2YncoEOoNXvcIwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTI1MDY0ODAwWhcNMjQxMTIzMDY0ODAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AMyLf6O5yyD9ipazq4TMaU/SESvetS6EYm/4L+OdbpMOSv+d/Y51mUiNjXOXMcsH
    qQTzXdcz1gH1ukC34n12aEtM4refBsdO/28eI0YY5ildNg9g1QIfBTvy2pQrxSaM
    nBKfIuvcJH2H3LP6Up3J+STkegROhQCmILVT8lxp/VwBjnQDpo9IjAGaF1RgkAl+
    O3L8XpJXeHlyiDSWGtQGgvib5Idv29ZWWlxt5LmgbVZJSz1HAR7E0aeAGXe4fPqr
    sobLkWD0hyLgW190CRm8imfI9DS2XdRC+IT7MAH69l3zLXDDynajenmoctGs5IeK
    yG76aegxOS8JCd9BznxMIF5j+n0trBm5UAMO2bAhIaMVwzzoK2PF8IhqKCZS34Wy
    IBtKAC+RokZE8OxKmSeYIPKEpxM/mRwn0oT3ubRs+aW3Yd4XLQTxDuy8aYozHNsa
    Nyi6AtQpyliiSgU3XdJEU+pf7upPZYnwrWexvQo0BrVVLgpDd1+/IUuPWg4Hso/i
    bLuqNEFDW63UpyEodmHYF6qgrRErmG+TX6nST0n27Kl4CJIr8tMsqDxrM6fxw4Ud
    EynHvS1zUmiG1hXn04iqAdy1yX6VGjQ4GzHsJDEdDYBdp4aKI+viTRDdtYoPNwhV
    x6jLxP9nNq+fNZFulz2Jq6pE9wjNnL8rmgC9LgWiYLyFAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRQG0BRN31sNTRc
    Z6cPuYfp5pYQTjANBgkqhkiG9w0BAQ0FAAOCAgEAuxH3n0w9zdw13NC4QBNliczi
    715kn9z8+c+at7UABdAqJos+Uv9sb4AJdiXmQxS8iuB4katNwx+lBF6ShUu9mUwm
    cNIF9GilkFImDCiGumrqCQUQzAvkyZIn4LQZgCbQn0wJZJtOQMjUG1JODy+BC3ZI
    BPGH+GMEr1SqfFOcJImWAVPFw9RqkCucwGo87w2GxA59u+K6KkRikDM/YV+mdYeY
    UP49zDlGDknayBzBUnk3+HUJURXca2KDz69kgISIztAt39Bp6vTY6IJPpqlBuw7Y
    MAiYZd6qnOvvdL2ck8Py54iIGJ+TBzF4f42sEr8gc8581jdJPJRbzEVhK75lXG6N
    emUJRJ5uj1DNflKaPL/yC2Z9O4/8gSIgW70Xe7HOvHVnGat2sp9GASmJpDHEk2vp
    V7gnd6aQHVz8UWCE8FgCJ9wQ9p36nvMiNAVvZSumI1VLU5tLITRdutR1pK7pey3/
    c3OUxvXV7dJ2vHtx9mKUW5UI4Ywx0ImUVOQPx827JG/9SCaeYNSfy8PiJKX5CeQZ
    HcfU81/1IlOygvaRsHPYAam1qHP3fRu238CcHUsxVx3DrlaUxmUr6TS1a/SpDwrK
    dkPV7bt4oGD4LqKc7GFljsYjwMvO08nZVREq3xXJnfrTitLsxGhpPlOi+m5xGsIC
    g81wl1YhF1iybTUsKrM=
    -----END CERTIFICATE-----
    
