apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
spec:
  template:
    spec:
      containers:
      - name: nvidia-device-plugin-ctr
        image: <%= $IMAGE %>
        imagePullPolicy: Always 
<% if [ "$IMAGE_PULL_SECRET" != "" ]; then -%>
      imagePullSecrets:
      - name: <%= $IMAGE_PULL_SECRET %>
<% fi -%>
