apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
spec:
  template:
    spec:
      containers:
      - name: nvidia-device-plugin-ctr
        image: <%= $(index image "nvidia/k8s-device-plugin:v0.6.0") %>
        imagePullPolicy: Always 
<% if [ $(index imagePullSecret "") != "" ]; then -%>
      imagePullSecrets:
      - name: <%= $(index imagePullSecret "registry-global-regcred") %>
<% fi -%>
