apiVersion: v1
name: nfs-drive
icon: file://icon.svg
description: Spawns an NFS server for use by applications.
keywords:
- nfs
- drive
- volume
maintainers:
- email: shawn.oneil@oregonstate.edu
  name: Shawn T O'Neil
version: 1.1.0
changeLog:
  v1.1.0:
    minor:
    - update deploy script to use more defaults
  v1.0:
    major:
    - First properly versioned chart (yay)
    minor:
    patch:
